### ISSUE TITLE
Correções Ortográficas, alíquota do ISS e outras sugestões

### ISSUE THREAD

**Issue by alibertoneto** [MrRafael/CLTxPJ#1]
- Salario -> Salário
- Slario -> Salário
- liquido -> líquido
- decimo -> décimo
- Deconto -> Desconto
- Beneficios -> Benefícios
- 13 Salario -> 13º Salário
- Ferias  -> Férias

Sugestão: 

1. De forma técnica, o imposto pelo simples nacional é um encargo e não um desconto. Vai haver o prolabore e dividendo contábil do PJ e vai haver uma despesa com o imposto.
2. Informar as alíquota. As tabelas mudam de alíquota conforme a receita bruta.
3. Informar a alíquota do ISS pago no município de emissão da NF

**Comment by MrRafael** [comment]
Ortografia corrigida -> https://github.com/MrRafael/CLTxPJ/commit/af4bf73ac69ce889a8825b60f9170a0218c3f224

Sobre a sugestão 1, seria mais sobre mudar a nomenclatura de desconto pra encargo ? https://github.com/MrRafael/CLTxPJ/commit/148937ecf6714301891da5fc655493d4d4bde2fe

2 -> https://github.com/MrRafael/CLTxPJ/commit/34e0031df0dda510d6bb934f4cdf921d653be5c8

Sobre ISS, esse imposto não esta embutido no encargo do simples nacional ? pago no DAS, por ex: Faturamento inicial cai na primeira alíquota do anexo III(caso use fator R), 6%, o ISS já não estaria dentro desses 6% ?

**Comment by alibertoneto** [comment]
Acho que são distintos, mesmo com o fator R, o ISS é pago ao município onde se emite a NF. O simples nacional é pago à União. (Aqui um contador vai esclarecer com certeza, até pq de município para município muda as regras e alíquotas)

A sugestão de usar encargo ao invés de desconto é para não haver confusão nos valores. O CNPJ recebe o valor (salário) integral, sem descontos. Os impostos são pagos depois e não descontados. Mas o resultado final é igual.

**Comment by MrRafael** [comment]
Consultei um contador referente ao ISS, no caso do simples nacional o valor já é recolhido no encargo do simples, com excessão de quando o ISS for retido pelo tomador do serviço, mas nesses casos se declara para não pagar duas vezes o imposto, então na prática a tarifa está "embutida" dentro da alíquota. Obrigado pelas sugestões, vou fechar o issue mas se necessário abra um novo.
